export enum EShoppingOption {
  // SHOPPING LIST OPTIONS
  RENAME_SHOPPING_LIST = 'RENAME_SHOPPING_LIST',
  // LOCATION OPTIONS
  REORDER_CATEGORIES = 'REORDER_CATEGORIES',
  RENAME_LOCATION = 'RENAME_LOCATION'
}
