export enum EShoppingOption {
  // SHOPPING LIST OPTIONS
  NEW_SHOPPING_LIST = 'NEW_SHOPPING_LIST',
  RENAME_SHOPPING_LIST = 'RENAME_SHOPPING_LIST',
  DELETE_SHOPPING_LIST = 'DELETE_SHOPPING_LIST',
  // LOCATION OPTIONS
  NEW_LOCATION = 'NEW_LOCATION',
  REORDER_CATEGORIES = 'REORDER_CATEGORIES',
  RENAME_LOCATION = 'RENAME_LOCATION',
}
